### ISSUE TITLE
Use setup node action

### ISSUE THREAD

**Issue by dylanpinn** [dylanpinn/typescript-react-cypress-example#289]
Example config.

```yaml
- uses: actions/setup-node@v3
  with:
    node-version: 14
```
